version: '2.4'
services:
 dns:
  container_name: coredns
  image: coredns/coredns
  ports:
   - '53:53/udp'  
  volumes:
   - ./Corefile:/etc/coredns/Corefile
  restart: always
  privileged: true
  entrypoint: 
   - '/coredns'
   - '-conf'
   - '/etc/coredns/Corefile'
